#!/bin/tcsh -f
echo " "
echo " "
echo "	***	 ********  ***   ***    ****	 ***   ***	"
echo "	***	***    *** ***  ***   ***  ***	 ***   ***	"
echo "	***	***    *** *** ***    ***   ***	 ***   ***	"
echo "	***	***    *** ******      ***	 ***   ***	"
echo "	***	********** ******       ***	 *********      "
echo "	***	********** ******	 ***	 *********      "
echo "	***	***    *** ***  ***	   ***	 ***   ***      "
echo "	***     ***    *** ***   ***  ***   ***	 ***   ***      "
echo "	******* ***    *** ***    ***  ***   *** ***   ***      "
echo "	******* ***    *** ***    ***	 ****	 ***   ***      "
echo " "
echo "		 Author : Lakshmi M S				"
echo " A TCL script to automate User Interface that will take RTL netlist & "
echo " SDC constraints as inputs and will generate synthnesized netlist & "
echo " pre-layout timing report as output. It uses Yosys and open Timer tools."
echo " "
echo " "

set my_work_dir = 'pwd'
#.................................................................#
#.................Tool Initialization.............................#
#.................................................................#
if ($#argv != 1) then
	echo "INFO: Please provide the csv file"
	exit 1
endif


if (! -f $argv[1] ) then
	echo "ERROR: Cannot find the csv file $argv[1], Exiting."
	exit 1
else if ($argv[1] == "-help") then
	echo Usage: ./laksh \<csv file\>
	echo 	where \<csv file\> consists of the following details
	echo 	\<Design Name\> is the name of Top level module
	echo	\<Output Directory\> is the output directory to dump the synthesized script, netlists and timing reports
	echo	\<Netlist Directory\> is the directory where all RTL netlists are present
	echo	\<Early Library Path\> is the path of early cell library used for STA
	echo	\<Late Library Path\> is the path of late cell library used for STA
	echo	\<Constraints File\> is the csv file for path constraints used for STA
	exit 1
else
	#echo "initiate TCL script from here"
	echo "	LAKSH - A automation tool for VLSI design synthesis	"
	tclsh lakshscript.tcl $argv[1]
endif

